# Data Preprocessing Tools

## Importing the libraries

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

## Importing the dataset

In [ ]:
dataset = pd.read_csv('Data.csv')
X = dataset.iloc[:, :-1].values # :-1 -> 마지막 열만 제외하고 모든 열을 가져옴(특성행렬)
y = dataset.iloc[:, -1].values  # 마지막 열만 가져오므로 범위(:) 필요없음

In [ ]:
print(X)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 nan]
 ['France' 35.0 58000.0]
 ['Spain' nan 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


In [ ]:
print(y)

['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']


## Taking care of missing data

In [12]:
#누락된 값이 평균값으로 대체됨
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy="mean") #결측값을 평균값으로
imputer.fit(X[:, 1:3]) #평균값으로 대체
X[:, 1:3] = imputer.transform(X[:, 1:3])

In [ ]:
print(X)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 63777.77777777778]
 ['France' 35.0 58000.0]
 ['Spain' 38.77777777777778 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


## Encoding categorical data

### Encoding the Independent Variable

In [13]:
#범주형 데이터 인코딩 (Country 문자열 -> 숫자로 변환)
#원핫인코딩 방식 사용
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [14]:
print(X)

[[1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [0.0 1.0 0.0 30.0 54000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 35.0 58000.0]
 [0.0 0.0 1.0 38.77777777777778 52000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


### Encoding the Dependent Variable

In [15]:
#범주형 데이터 인코딩 (Purchased(yes/No) -> 숫자로 변환)
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [16]:
print(y)

[0 1 0 0 1 1 0 1 0 1]


## Splitting the dataset into the Training set and Test set

In [17]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 1)
#test_size(분할비) /

In [18]:
print(X_train)  #훈련 세트의 특성 행렬

[[0.0 0.0 1.0 38.77777777777778 52000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 35.0 58000.0]]


In [19]:
print(X_test) #테스트 세트의 특성 행렬(관측치 2개)

[[0.0 1.0 0.0 30.0 54000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


In [20]:
print(y_train)  #훈련 세트의 종속변수(8개의 구매여부)

[0 1 0 0 1 1 0 1]


In [21]:
print(y_test) #테스트 세트의 종속변수

[0 1]


## Feature Scaling

In [22]:
#표준화 : 항상 좋은 결과 도출
#정규화 : 대부분의 특성이 정규 분포를 따른다면 정규화가 좋음(only 특수상황)

In [23]:
#from sklearn.preprocessing import StandardScaler
#sc = StandardScaler() #클래스(매개변수 필요없음)
#평균과 표준편차를 구해 특성의 모든 값에 식 적용

#X_train = sc.fit_transform(X_train)
#X_train[:, 3:] = sc.fit_transform(X_train[:, 3:])
#연령의 인덱스 3부터 시작해 모든 열을 가져옴
#오브젝트 sc의 fit 메소드를 사용해 X_train 특성의 연령과 급여의 평균을 구하고 연령과 급여의 표준편차를 구한다.(모든 값의 평균과 표준편차 구함)
#가변수에는 특성 스케일링을 적용하지 않으므로 연령과 급여 열에만 적용

#X_test = sc.transform(X_test)
# test set는 배포 후 관측하는 새로운 데이터이므로 transform 메소드만 적용

In [ ]:
# Q : 특성 행렬의 가변수에도 특성 스케일링의 표준화를 적용해야 하는지 여부!!
# A : 적용하지 않는다. 특성 스케일링을 하는 표준화의 목적이 모든 특성의 값을 동일한 범위로 변환하는 것이기 때문
# 표준화는 모든 특성의 값을 -3에서 3사이로 변환한다. 반면 가변수는 1과 0으로 구성되므로 이미 값이 -3에서 3이므로 표준화를 적용해도 의미없음..
# 심지어 표준화를 적용하게 되면 값을 -3에서 3사이로 변환하기는 하짐나 각 변수가 가지는 의미가 사라지므로 표준화를 적용하면 안됨,,
# -> 관측치의 국적이 무엇인지 알 수 없게 됨
## 훈련 성능 저하되므로 반드시 숫자형 값에만 특성 스케일링을 적용하도록!!(가변수는 그대로 둔다.)
# X_train과 X_test에 특성 스케일링 적용

In [24]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train[:, 3:] = sc.fit_transform(X_train[:, 3:])
X_test[:, 3:] =  sc.transform(X_test[:, 3:])

In [25]:
print(X_train)

[[0.0 0.0 1.0 -0.19159184384578545 -1.0781259408412425]
 [0.0 1.0 0.0 -0.014117293757057777 -0.07013167641635372]
 [1.0 0.0 0.0 0.566708506533324 0.633562432710455]
 [0.0 0.0 1.0 -0.30453019390224867 -0.30786617274297867]
 [0.0 0.0 1.0 -1.9018011447007988 -1.420463615551582]
 [1.0 0.0 0.0 1.1475343068237058 1.232653363453549]
 [0.0 1.0 0.0 1.4379472069688968 1.5749910381638885]
 [1.0 0.0 0.0 -0.7401495441200351 -0.5646194287757332]]


In [26]:
print(X_test)

[[0.0 1.0 0.0 -1.4661817944830124 -0.9069571034860727]
 [1.0 0.0 0.0 -0.44973664397484414 0.2056403393225306]]
